kind: Deployment
apiVersion: apps/v1
metadata:
  name: kubesphere
  namespace: ovens-v6
  labels:
    app: kubesphere
  annotations:
    deployment.kubernetes.io/revision: '1'
    kubesphere.io/creator: zhaobo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubesphere
  template:
    metadata:
      labels:
        app: kubesphere
    spec:
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
            type: ''
      containers:
        - name: kubesphere
          image: "$REGISTRY/$DOCKERHUB_NAMESPACE/$APP_NAME:SNAPSHOT-$BRANCH_NAME-$BUILD_NUMBER"
          ports:
            - name: http-8080
              containerPort: 8080
              protocol: TCP
          env:
            - name: CACHE_IGNORE
              value: js|html
            - name: CACHE_PUBLIC_EXPIRATION
              value: 3d
          resources:
            limits:
              cpu: 300m
              memory: 600Mi
            requests:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
            - name: host-time
              readOnly: true
              mountPath: /etc/localtime
          readinessProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            timeoutSeconds: 10
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 30
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: default
      serviceAccount: default
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
apiVersion: v1
kind: Service
metadata:
  namespace: ovens-v6
  labels:
    app: kubesphere-svc
  name: kubesphere-svc
spec:
  sessionAffinity: None
  selector:
    app: kubesphere
  ports:
    - name: http-8080
      protocol: TCP
      targetPort: 8080
      port: 8080
      nodePort: 30861
  type: NodePort
